### ISSUE TITLE
Interfaces for languages beyond Rust

### ISSUE THREAD

**Issue by mhx** [facebookincubator/superconsole#10]
This is *exactly* the library I've been looking for. However, I'd need to include it in a C++ project.

I don't have a lot of experience with Rust, so I'm not sure how viable it would be to make the superconsole interface available to languages like C++ or Python without having to re-write large parts of the core.

Any feedback on the viability would be appreciated.

**Comment by stepancheg** [comment]
I think the value of superconsole is in idea, but implementation is quite simple, and it is just 4KLOC, and half of it is rather simple "components". Rewriting in C++/Python by copy-paste might be easier than building a bridge and dealing with interface mapping between languages. Additionally, Rust idiom may not fit perfectly into Python or C++.

**Comment by mhx** [comment]
Thanks for the feedback, appreciate it!
