### ISSUE TITLE
State is not very type safe

### ISSUE THREAD

**Issue by wilfreddenton** [facebookincubator/superconsole#6]
As i stated in my other issue [#5] I'm very much enjoying using this library. Thanks again!

I would love to have some more type safety around `state`. If I decide to change the type of some piece of state, the compiler isn't going to complain and I will hit runtime errors. If `state` were instead a generic type then I could fill that in with the state type for my app and run into these errors at compile time.

**Comment by cjhopman** [comment]
Glad to hear you're enjoying the library!

In buck we've also struggled with the lack of type safety in state, I think changing it to be a generic type provided by the app would be a great change. I expect making that change would parameterize all the places that would need to be parameterized to support the user specifying the error type as well.

**Comment by stepancheg** [comment]
New version of `superconsole` has no `State`: d586d6f7f366c5e0eb3c84d73da221c12097520b.

API changed. Now `SuperConsole::new(..)` no longer grabs the component to render. Instead, `super_console.render(..)` takes the component reference. And that component can grab whatever it wants.

Like this:

```rust
let super_console = SuperConsole::new();

for i in 0..100 {
  super_console.render(&MyComponent {
    counter: i,
  });
}
```
